<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/digota/digota/order/orderpb/order.proto

namespace Orderpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>orderpb.ListRequest</code>
 */
class ListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int64 page = 1;</code>
     */
    private $page = 0;
    /**
     * <code>int64 limit = 2;</code>
     */
    private $limit = 0;
    /**
     * <code>.orderpb.ListRequest.Sort sort = 3;</code>
     */
    private $sort = 0;

    public function __construct() {
        \GPBMetadata\GithubCom\Digota\Digota\Order\Orderpb\Order::initOnce();
        parent::__construct();
    }

    /**
     * <code>int64 page = 1;</code>
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * <code>int64 page = 1;</code>
     */
    public function setPage($var)
    {
        GPBUtil::checkInt64($var);
        $this->page = $var;
    }

    /**
     * <code>int64 limit = 2;</code>
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * <code>int64 limit = 2;</code>
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt64($var);
        $this->limit = $var;
    }

    /**
     * <code>.orderpb.ListRequest.Sort sort = 3;</code>
     */
    public function getSort()
    {
        return $this->sort;
    }

    /**
     * <code>.orderpb.ListRequest.Sort sort = 3;</code>
     */
    public function setSort($var)
    {
        GPBUtil::checkEnum($var, \Orderpb\ListRequest_Sort::class);
        $this->sort = $var;
    }

}

