<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/digota/digota/order/orderpb/order.proto

namespace Orderpb;

/**
 * Protobuf enum <code>orderpb.OrderItem.Type</code>
 */
class OrderItem_Type
{
    /**
     * <code>reserved = 0;</code>
     */
    const reserved = 0;
    /**
     * <code>sku = 1;</code>
     */
    const sku = 1;
    /**
     * <code>discount = 2;</code>
     */
    const discount = 2;
    /**
     * <code>tax = 3;</code>
     */
    const tax = 3;
    /**
     * <code>shipping = 4;</code>
     */
    const shipping = 4;
}

