<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/digota/digota/order/orderpb/order.proto

namespace Orderpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>orderpb.OrderItem</code>
 */
class OrderItem extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.orderpb.OrderItem.Type type = 1;</code>
     */
    private $type = 0;
    /**
     * <code>int64 quantity = 2;</code>
     */
    private $quantity = 0;
    /**
     * <code>int64 amount = 3;</code>
     */
    private $amount = 0;
    /**
     * <code>.paymentpb.Currency currency = 4;</code>
     */
    private $currency = 0;
    /**
     * <code>string parent = 5;</code>
     */
    private $parent = '';
    /**
     * <code>string description = 6;</code>
     */
    private $description = '';

    public function __construct() {
        \GPBMetadata\GithubCom\Digota\Digota\Order\Orderpb\Order::initOnce();
        parent::__construct();
    }

    /**
     * <code>.orderpb.OrderItem.Type type = 1;</code>
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * <code>.orderpb.OrderItem.Type type = 1;</code>
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Orderpb\OrderItem_Type::class);
        $this->type = $var;
    }

    /**
     * <code>int64 quantity = 2;</code>
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * <code>int64 quantity = 2;</code>
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt64($var);
        $this->quantity = $var;
    }

    /**
     * <code>int64 amount = 3;</code>
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * <code>int64 amount = 3;</code>
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;
    }

    /**
     * <code>.paymentpb.Currency currency = 4;</code>
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * <code>.paymentpb.Currency currency = 4;</code>
     */
    public function setCurrency($var)
    {
        GPBUtil::checkEnum($var, \Paymentpb\Currency::class);
        $this->currency = $var;
    }

    /**
     * <code>string parent = 5;</code>
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * <code>string parent = 5;</code>
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;
    }

    /**
     * <code>string description = 6;</code>
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * <code>string description = 6;</code>
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;
    }

}

