<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/digota/digota/order/orderpb/order.proto

namespace Orderpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>orderpb.Order</code>
 */
class Order extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * <code>int64 amount = 2;</code>
     */
    private $amount = 0;
    /**
     * <code>.paymentpb.Currency currency = 3;</code>
     */
    private $currency = 0;
    /**
     * <code>repeated .orderpb.OrderItem items = 4;</code>
     */
    private $items;
    /**
     * <code>map&lt;string, string&gt; metadata = 5;</code>
     */
    private $metadata;
    /**
     * <code>string email = 6;</code>
     */
    private $email = '';
    /**
     * <code>string chargeId = 7;</code>
     */
    private $chargeId = '';
    /**
     * <code>.orderpb.Order.status Status = 8;</code>
     */
    private $Status = 0;
    /**
     * <code>.orderpb.Shipping shipping = 9;</code>
     */
    private $shipping = null;
    /**
     * <code>int64 created = 998;</code>
     */
    private $created = 0;
    /**
     * <code>int64 updated = 999;</code>
     */
    private $updated = 0;

    public function __construct() {
        \GPBMetadata\GithubCom\Digota\Digota\Order\Orderpb\Order::initOnce();
        parent::__construct();
    }

    /**
     * <code>string id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>string id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;
    }

    /**
     * <code>int64 amount = 2;</code>
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * <code>int64 amount = 2;</code>
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;
    }

    /**
     * <code>.paymentpb.Currency currency = 3;</code>
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * <code>.paymentpb.Currency currency = 3;</code>
     */
    public function setCurrency($var)
    {
        GPBUtil::checkEnum($var, \Paymentpb\Currency::class);
        $this->currency = $var;
    }

    /**
     * <code>repeated .orderpb.OrderItem items = 4;</code>
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * <code>repeated .orderpb.OrderItem items = 4;</code>
     */
    public function setItems(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Orderpb\OrderItem::class);
        $this->items = $arr;
    }

    /**
     * <code>map&lt;string, string&gt; metadata = 5;</code>
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * <code>map&lt;string, string&gt; metadata = 5;</code>
     */
    public function setMetadata(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->metadata = $arr;
    }

    /**
     * <code>string email = 6;</code>
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * <code>string email = 6;</code>
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;
    }

    /**
     * <code>string chargeId = 7;</code>
     */
    public function getChargeId()
    {
        return $this->chargeId;
    }

    /**
     * <code>string chargeId = 7;</code>
     */
    public function setChargeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->chargeId = $var;
    }

    /**
     * <code>.orderpb.Order.status Status = 8;</code>
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * <code>.orderpb.Order.status Status = 8;</code>
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Orderpb\Order_status::class);
        $this->Status = $var;
    }

    /**
     * <code>.orderpb.Shipping shipping = 9;</code>
     */
    public function getShipping()
    {
        return $this->shipping;
    }

    /**
     * <code>.orderpb.Shipping shipping = 9;</code>
     */
    public function setShipping(&$var)
    {
        GPBUtil::checkMessage($var, \Orderpb\Shipping::class);
        $this->shipping = $var;
    }

    /**
     * <code>int64 created = 998;</code>
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * <code>int64 created = 998;</code>
     */
    public function setCreated($var)
    {
        GPBUtil::checkInt64($var);
        $this->created = $var;
    }

    /**
     * <code>int64 updated = 999;</code>
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * <code>int64 updated = 999;</code>
     */
    public function setUpdated($var)
    {
        GPBUtil::checkInt64($var);
        $this->updated = $var;
    }

}

