<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order/orderpb/order.proto

namespace Orderpb;

/**
 * Protobuf enum <code>orderpb.listRequest.Sort</code>
 */
class listRequest_Sort
{
    /**
     * <code>Natural = 0;</code>
     */
    const Natural = 0;
    /**
     * <code>CreatedDesc = 1;</code>
     */
    const CreatedDesc = 1;
    /**
     * <code>CreatedAsc = 2;</code>
     */
    const CreatedAsc = 2;
    /**
     * <code>UpdatedDesc = 3;</code>
     */
    const UpdatedDesc = 3;
    /**
     * <code>UpdatedAsc = 4;</code>
     */
    const UpdatedAsc = 4;
}

