<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order/orderpb/order.proto

namespace Orderpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>orderpb.newRequest</code>
 */
class newRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.paymentpb.currency currency = 1 [(.gogoproto.moretags) = "validate:&#92;"required,gte=1,lte=128&#92;""];</code>
     */
    private $currency = 0;
    /**
     * <code>repeated .orderpb.orderItem items = 2 [(.gogoproto.moretags) = "bson:&#92;"items&#92;" validate:&#92;"dive,required&#92;""];</code>
     */
    private $items;
    /**
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */
    private $metadata;
    /**
     * <code>string email = 4 [(.gogoproto.moretags) = "validate:&#92;"omitempty,email&#92;""];</code>
     */
    private $email = '';
    /**
     * <code>.orderpb.shipping shipping = 5 [(.gogoproto.moretags) = "validate:&#92;"omitempty,dive&#92;""];</code>
     */
    private $shipping = null;

    public function __construct() {
        \GPBMetadata\Order\Orderpb\Order::initOnce();
        parent::__construct();
    }

    /**
     * <code>.paymentpb.currency currency = 1 [(.gogoproto.moretags) = "validate:&#92;"required,gte=1,lte=128&#92;""];</code>
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * <code>.paymentpb.currency currency = 1 [(.gogoproto.moretags) = "validate:&#92;"required,gte=1,lte=128&#92;""];</code>
     */
    public function setCurrency($var)
    {
        GPBUtil::checkEnum($var, \Paymentpb\currency::class);
        $this->currency = $var;
    }

    /**
     * <code>repeated .orderpb.orderItem items = 2 [(.gogoproto.moretags) = "bson:&#92;"items&#92;" validate:&#92;"dive,required&#92;""];</code>
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * <code>repeated .orderpb.orderItem items = 2 [(.gogoproto.moretags) = "bson:&#92;"items&#92;" validate:&#92;"dive,required&#92;""];</code>
     */
    public function setItems(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Orderpb\orderItem::class);
        $this->items = $arr;
    }

    /**
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * <code>map&lt;string, string&gt; metadata = 3;</code>
     */
    public function setMetadata(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->metadata = $arr;
    }

    /**
     * <code>string email = 4 [(.gogoproto.moretags) = "validate:&#92;"omitempty,email&#92;""];</code>
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * <code>string email = 4 [(.gogoproto.moretags) = "validate:&#92;"omitempty,email&#92;""];</code>
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;
    }

    /**
     * <code>.orderpb.shipping shipping = 5 [(.gogoproto.moretags) = "validate:&#92;"omitempty,dive&#92;""];</code>
     */
    public function getShipping()
    {
        return $this->shipping;
    }

    /**
     * <code>.orderpb.shipping shipping = 5 [(.gogoproto.moretags) = "validate:&#92;"omitempty,dive&#92;""];</code>
     */
    public function setShipping(&$var)
    {
        GPBUtil::checkMessage($var, \Orderpb\shipping::class);
        $this->shipping = $var;
    }

}

