<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order/orderpb/order.proto

namespace Orderpb;

/**
 * Protobuf enum <code>orderpb.order.status</code>
 */
class order_status
{
    /**
     * <code>Created = 0;</code>
     */
    const Created = 0;
    /**
     * <code>Paid = 1;</code>
     */
    const Paid = 1;
    /**
     * <code>Canceled = 2;</code>
     */
    const Canceled = 2;
    /**
     * <code>Fulfilled = 3;</code>
     */
    const Fulfilled = 3;
    /**
     * <code>Returned = 4;</code>
     */
    const Returned = 4;
}

