<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order/orderpb/order.proto

namespace Orderpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>orderpb.orderItem</code>
 */
class orderItem extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.orderpb.orderItem.Type type = 1 [(.gogoproto.moretags) = "validate:&#92;"required,gte=1,lte=4&#92;""];</code>
     */
    private $type = 0;
    /**
     * <code>int64 quantity = 2 [(.gogoproto.moretags) = "validate:&#92;"omitempty,gte=0&#92;""];</code>
     */
    private $quantity = 0;
    /**
     * <code>int64 amount = 3;</code>
     */
    private $amount = 0;
    /**
     * <code>.paymentpb.currency currency = 4 [(.gogoproto.moretags) = "validate:&#92;"omitempty,gte=1,lte=128&#92;""];</code>
     */
    private $currency = 0;
    /**
     * <code>string parent = 5 [(.gogoproto.moretags) = "validate:&#92;"omitempty,uuid4&#92;""];</code>
     */
    private $parent = '';
    /**
     * <code>string description = 6;</code>
     */
    private $description = '';

    public function __construct() {
        \GPBMetadata\Order\Orderpb\Order::initOnce();
        parent::__construct();
    }

    /**
     * <code>.orderpb.orderItem.Type type = 1 [(.gogoproto.moretags) = "validate:&#92;"required,gte=1,lte=4&#92;""];</code>
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * <code>.orderpb.orderItem.Type type = 1 [(.gogoproto.moretags) = "validate:&#92;"required,gte=1,lte=4&#92;""];</code>
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Orderpb\orderItem_Type::class);
        $this->type = $var;
    }

    /**
     * <code>int64 quantity = 2 [(.gogoproto.moretags) = "validate:&#92;"omitempty,gte=0&#92;""];</code>
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * <code>int64 quantity = 2 [(.gogoproto.moretags) = "validate:&#92;"omitempty,gte=0&#92;""];</code>
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt64($var);
        $this->quantity = $var;
    }

    /**
     * <code>int64 amount = 3;</code>
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * <code>int64 amount = 3;</code>
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;
    }

    /**
     * <code>.paymentpb.currency currency = 4 [(.gogoproto.moretags) = "validate:&#92;"omitempty,gte=1,lte=128&#92;""];</code>
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * <code>.paymentpb.currency currency = 4 [(.gogoproto.moretags) = "validate:&#92;"omitempty,gte=1,lte=128&#92;""];</code>
     */
    public function setCurrency($var)
    {
        GPBUtil::checkEnum($var, \Paymentpb\currency::class);
        $this->currency = $var;
    }

    /**
     * <code>string parent = 5 [(.gogoproto.moretags) = "validate:&#92;"omitempty,uuid4&#92;""];</code>
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * <code>string parent = 5 [(.gogoproto.moretags) = "validate:&#92;"omitempty,uuid4&#92;""];</code>
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;
    }

    /**
     * <code>string description = 6;</code>
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * <code>string description = 6;</code>
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;
    }

}

