<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order/orderpb/order.proto

namespace Orderpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>orderpb.shipping</code>
 */
class shipping extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string name = 1;</code>
     */
    private $name = '';
    /**
     * <code>string phone = 2;</code>
     */
    private $phone = '';
    /**
     * <code>.orderpb.shipping.Address address = 3;</code>
     */
    private $address = null;
    /**
     * <code>string carrier = 4;</code>
     */
    private $carrier = '';
    /**
     * <code>string trackingNumber = 5;</code>
     */
    private $trackingNumber = '';

    public function __construct() {
        \GPBMetadata\Order\Orderpb\Order::initOnce();
        parent::__construct();
    }

    /**
     * <code>string name = 1;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <code>string name = 1;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <code>string phone = 2;</code>
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * <code>string phone = 2;</code>
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;
    }

    /**
     * <code>.orderpb.shipping.Address address = 3;</code>
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * <code>.orderpb.shipping.Address address = 3;</code>
     */
    public function setAddress(&$var)
    {
        GPBUtil::checkMessage($var, \Orderpb\shipping_Address::class);
        $this->address = $var;
    }

    /**
     * <code>string carrier = 4;</code>
     */
    public function getCarrier()
    {
        return $this->carrier;
    }

    /**
     * <code>string carrier = 4;</code>
     */
    public function setCarrier($var)
    {
        GPBUtil::checkString($var, True);
        $this->carrier = $var;
    }

    /**
     * <code>string trackingNumber = 5;</code>
     */
    public function getTrackingNumber()
    {
        return $this->trackingNumber;
    }

    /**
     * <code>string trackingNumber = 5;</code>
     */
    public function setTrackingNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->trackingNumber = $var;
    }

}

