<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order/orderpb/order.proto

namespace Orderpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>orderpb.shipping.Address</code>
 */
class shipping_Address extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string line1 = 1;</code>
     */
    private $line1 = '';
    /**
     * <code>string city = 2;</code>
     */
    private $city = '';
    /**
     * <code>string country = 3;</code>
     */
    private $country = '';
    /**
     * <code>string line2 = 4;</code>
     */
    private $line2 = '';
    /**
     * <code>string postalCode = 5;</code>
     */
    private $postalCode = '';
    /**
     * <code>string state = 6;</code>
     */
    private $state = '';

    public function __construct() {
        \GPBMetadata\Order\Orderpb\Order::initOnce();
        parent::__construct();
    }

    /**
     * <code>string line1 = 1;</code>
     */
    public function getLine1()
    {
        return $this->line1;
    }

    /**
     * <code>string line1 = 1;</code>
     */
    public function setLine1($var)
    {
        GPBUtil::checkString($var, True);
        $this->line1 = $var;
    }

    /**
     * <code>string city = 2;</code>
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * <code>string city = 2;</code>
     */
    public function setCity($var)
    {
        GPBUtil::checkString($var, True);
        $this->city = $var;
    }

    /**
     * <code>string country = 3;</code>
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * <code>string country = 3;</code>
     */
    public function setCountry($var)
    {
        GPBUtil::checkString($var, True);
        $this->country = $var;
    }

    /**
     * <code>string line2 = 4;</code>
     */
    public function getLine2()
    {
        return $this->line2;
    }

    /**
     * <code>string line2 = 4;</code>
     */
    public function setLine2($var)
    {
        GPBUtil::checkString($var, True);
        $this->line2 = $var;
    }

    /**
     * <code>string postalCode = 5;</code>
     */
    public function getPostalCode()
    {
        return $this->postalCode;
    }

    /**
     * <code>string postalCode = 5;</code>
     */
    public function setPostalCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->postalCode = $var;
    }

    /**
     * <code>string state = 6;</code>
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * <code>string state = 6;</code>
     */
    public function setState($var)
    {
        GPBUtil::checkString($var, True);
        $this->state = $var;
    }

}

