<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/digota/digota/payment/paymentpb/payment.proto

namespace Paymentpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>paymentpb.Card</code>
 */
class Card extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string Number = 1;</code>
     */
    private $Number = '';
    /**
     * <code>string ExpireMonth = 2;</code>
     */
    private $ExpireMonth = '';
    /**
     * <code>string ExpireYear = 3;</code>
     */
    private $ExpireYear = '';
    /**
     * <code>string FirstName = 4;</code>
     */
    private $FirstName = '';
    /**
     * <code>string LastName = 5;</code>
     */
    private $LastName = '';
    /**
     * <code>string CVC = 6;</code>
     */
    private $CVC = '';
    /**
     * <code>.paymentpb.CardType type = 8;</code>
     */
    private $type = 0;

    public function __construct() {
        \GPBMetadata\GithubCom\Digota\Digota\Payment\Paymentpb\Payment::initOnce();
        parent::__construct();
    }

    /**
     * <code>string Number = 1;</code>
     */
    public function getNumber()
    {
        return $this->Number;
    }

    /**
     * <code>string Number = 1;</code>
     */
    public function setNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->Number = $var;
    }

    /**
     * <code>string ExpireMonth = 2;</code>
     */
    public function getExpireMonth()
    {
        return $this->ExpireMonth;
    }

    /**
     * <code>string ExpireMonth = 2;</code>
     */
    public function setExpireMonth($var)
    {
        GPBUtil::checkString($var, True);
        $this->ExpireMonth = $var;
    }

    /**
     * <code>string ExpireYear = 3;</code>
     */
    public function getExpireYear()
    {
        return $this->ExpireYear;
    }

    /**
     * <code>string ExpireYear = 3;</code>
     */
    public function setExpireYear($var)
    {
        GPBUtil::checkString($var, True);
        $this->ExpireYear = $var;
    }

    /**
     * <code>string FirstName = 4;</code>
     */
    public function getFirstName()
    {
        return $this->FirstName;
    }

    /**
     * <code>string FirstName = 4;</code>
     */
    public function setFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->FirstName = $var;
    }

    /**
     * <code>string LastName = 5;</code>
     */
    public function getLastName()
    {
        return $this->LastName;
    }

    /**
     * <code>string LastName = 5;</code>
     */
    public function setLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->LastName = $var;
    }

    /**
     * <code>string CVC = 6;</code>
     */
    public function getCVC()
    {
        return $this->CVC;
    }

    /**
     * <code>string CVC = 6;</code>
     */
    public function setCVC($var)
    {
        GPBUtil::checkString($var, True);
        $this->CVC = $var;
    }

    /**
     * <code>.paymentpb.CardType type = 8;</code>
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * <code>.paymentpb.CardType type = 8;</code>
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Paymentpb\CardType::class);
        $this->type = $var;
    }

}

