<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/digota/digota/payment/paymentpb/payment.proto

namespace Paymentpb;

/**
 * Protobuf enum <code>paymentpb.CardType</code>
 */
class CardType
{
    /**
     * <code>CARD_Reserved = 0;</code>
     */
    const CARD_Reserved = 0;
    /**
     * <code>Mastercard = 1;</code>
     */
    const Mastercard = 1;
    /**
     * <code>Visa = 2;</code>
     */
    const Visa = 2;
    /**
     * <code>AmericanExpress = 3;</code>
     */
    const AmericanExpress = 3;
    /**
     * <code>JCB = 4;</code>
     */
    const JCB = 4;
    /**
     * <code>Discover = 5;</code>
     */
    const Discover = 5;
    /**
     * <code>DinersClub = 6;</code>
     */
    const DinersClub = 6;
}

