<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/digota/digota/payment/paymentpb/payment.proto

namespace Paymentpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>paymentpb.Charge</code>
 */
class Charge extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * <code>string statement = 2;</code>
     */
    private $statement = '';
    /**
     * <code>uint64 chargeAmount = 3;</code>
     */
    private $chargeAmount = 0;
    /**
     * <code>uint64 refundAmount = 4;</code>
     */
    private $refundAmount = 0;
    /**
     * <code>repeated .paymentpb.Refund refunds = 5;</code>
     */
    private $refunds;
    /**
     * <code>.paymentpb.Currency currency = 6;</code>
     */
    private $currency = 0;
    /**
     * <code>string email = 7;</code>
     */
    private $email = '';
    /**
     * <code>bool paid = 8;</code>
     */
    private $paid = false;
    /**
     * <code>bool refunded = 9;</code>
     */
    private $refunded = false;
    /**
     * <code>.paymentpb.PaymentProviderId providerId = 10;</code>
     */
    private $providerId = 0;
    /**
     * <code>string providerChargeId = 11;</code>
     */
    private $providerChargeId = '';
    /**
     * <code>int64 created = 998;</code>
     */
    private $created = 0;
    /**
     * <code>int64 updated = 999;</code>
     */
    private $updated = 0;

    public function __construct() {
        \GPBMetadata\GithubCom\Digota\Digota\Payment\Paymentpb\Payment::initOnce();
        parent::__construct();
    }

    /**
     * <code>string id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>string id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;
    }

    /**
     * <code>string statement = 2;</code>
     */
    public function getStatement()
    {
        return $this->statement;
    }

    /**
     * <code>string statement = 2;</code>
     */
    public function setStatement($var)
    {
        GPBUtil::checkString($var, True);
        $this->statement = $var;
    }

    /**
     * <code>uint64 chargeAmount = 3;</code>
     */
    public function getChargeAmount()
    {
        return $this->chargeAmount;
    }

    /**
     * <code>uint64 chargeAmount = 3;</code>
     */
    public function setChargeAmount($var)
    {
        GPBUtil::checkUint64($var);
        $this->chargeAmount = $var;
    }

    /**
     * <code>uint64 refundAmount = 4;</code>
     */
    public function getRefundAmount()
    {
        return $this->refundAmount;
    }

    /**
     * <code>uint64 refundAmount = 4;</code>
     */
    public function setRefundAmount($var)
    {
        GPBUtil::checkUint64($var);
        $this->refundAmount = $var;
    }

    /**
     * <code>repeated .paymentpb.Refund refunds = 5;</code>
     */
    public function getRefunds()
    {
        return $this->refunds;
    }

    /**
     * <code>repeated .paymentpb.Refund refunds = 5;</code>
     */
    public function setRefunds(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Paymentpb\Refund::class);
        $this->refunds = $arr;
    }

    /**
     * <code>.paymentpb.Currency currency = 6;</code>
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * <code>.paymentpb.Currency currency = 6;</code>
     */
    public function setCurrency($var)
    {
        GPBUtil::checkEnum($var, \Paymentpb\Currency::class);
        $this->currency = $var;
    }

    /**
     * <code>string email = 7;</code>
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * <code>string email = 7;</code>
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;
    }

    /**
     * <code>bool paid = 8;</code>
     */
    public function getPaid()
    {
        return $this->paid;
    }

    /**
     * <code>bool paid = 8;</code>
     */
    public function setPaid($var)
    {
        GPBUtil::checkBool($var);
        $this->paid = $var;
    }

    /**
     * <code>bool refunded = 9;</code>
     */
    public function getRefunded()
    {
        return $this->refunded;
    }

    /**
     * <code>bool refunded = 9;</code>
     */
    public function setRefunded($var)
    {
        GPBUtil::checkBool($var);
        $this->refunded = $var;
    }

    /**
     * <code>.paymentpb.PaymentProviderId providerId = 10;</code>
     */
    public function getProviderId()
    {
        return $this->providerId;
    }

    /**
     * <code>.paymentpb.PaymentProviderId providerId = 10;</code>
     */
    public function setProviderId($var)
    {
        GPBUtil::checkEnum($var, \Paymentpb\PaymentProviderId::class);
        $this->providerId = $var;
    }

    /**
     * <code>string providerChargeId = 11;</code>
     */
    public function getProviderChargeId()
    {
        return $this->providerChargeId;
    }

    /**
     * <code>string providerChargeId = 11;</code>
     */
    public function setProviderChargeId($var)
    {
        GPBUtil::checkString($var, True);
        $this->providerChargeId = $var;
    }

    /**
     * <code>int64 created = 998;</code>
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * <code>int64 created = 998;</code>
     */
    public function setCreated($var)
    {
        GPBUtil::checkInt64($var);
        $this->created = $var;
    }

    /**
     * <code>int64 updated = 999;</code>
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * <code>int64 updated = 999;</code>
     */
    public function setUpdated($var)
    {
        GPBUtil::checkInt64($var);
        $this->updated = $var;
    }

}

