<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/digota/digota/payment/paymentpb/payment.proto

namespace Paymentpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>paymentpb.ChargeRequest</code>
 */
class ChargeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.paymentpb.Currency currency = 1;</code>
     */
    private $currency = 0;
    /**
     * <code>uint64 total = 2;</code>
     */
    private $total = 0;
    /**
     * <code>.paymentpb.Card Card = 3;</code>
     */
    private $Card = null;
    /**
     * <code>string email = 4;</code>
     */
    private $email = '';
    /**
     * <code>string statement = 5;</code>
     */
    private $statement = '';
    /**
     * <code>.paymentpb.PaymentProviderId paymentProviderId = 6;</code>
     */
    private $paymentProviderId = 0;
    /**
     * <code>map&lt;string, string&gt; metadata = 7;</code>
     */
    private $metadata;

    public function __construct() {
        \GPBMetadata\GithubCom\Digota\Digota\Payment\Paymentpb\Payment::initOnce();
        parent::__construct();
    }

    /**
     * <code>.paymentpb.Currency currency = 1;</code>
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * <code>.paymentpb.Currency currency = 1;</code>
     */
    public function setCurrency($var)
    {
        GPBUtil::checkEnum($var, \Paymentpb\Currency::class);
        $this->currency = $var;
    }

    /**
     * <code>uint64 total = 2;</code>
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * <code>uint64 total = 2;</code>
     */
    public function setTotal($var)
    {
        GPBUtil::checkUint64($var);
        $this->total = $var;
    }

    /**
     * <code>.paymentpb.Card Card = 3;</code>
     */
    public function getCard()
    {
        return $this->Card;
    }

    /**
     * <code>.paymentpb.Card Card = 3;</code>
     */
    public function setCard(&$var)
    {
        GPBUtil::checkMessage($var, \Paymentpb\Card::class);
        $this->Card = $var;
    }

    /**
     * <code>string email = 4;</code>
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * <code>string email = 4;</code>
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;
    }

    /**
     * <code>string statement = 5;</code>
     */
    public function getStatement()
    {
        return $this->statement;
    }

    /**
     * <code>string statement = 5;</code>
     */
    public function setStatement($var)
    {
        GPBUtil::checkString($var, True);
        $this->statement = $var;
    }

    /**
     * <code>.paymentpb.PaymentProviderId paymentProviderId = 6;</code>
     */
    public function getPaymentProviderId()
    {
        return $this->paymentProviderId;
    }

    /**
     * <code>.paymentpb.PaymentProviderId paymentProviderId = 6;</code>
     */
    public function setPaymentProviderId($var)
    {
        GPBUtil::checkEnum($var, \Paymentpb\PaymentProviderId::class);
        $this->paymentProviderId = $var;
    }

    /**
     * <code>map&lt;string, string&gt; metadata = 7;</code>
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * <code>map&lt;string, string&gt; metadata = 7;</code>
     */
    public function setMetadata(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->metadata = $arr;
    }

}

