<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/digota/digota/payment/paymentpb/payment.proto

namespace Paymentpb;

/**
 * Protobuf enum <code>paymentpb.ChargeStatus</code>
 */
class ChargeStatus
{
    /**
     * <code>Paid = 0;</code>
     */
    const Paid = 0;
    /**
     * <code>Refunded = 1;</code>
     */
    const Refunded = 1;
}

