<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/digota/digota/payment/paymentpb/payment.proto

namespace Paymentpb;

/**
 * Protobuf enum <code>paymentpb.RefundReason</code>
 */
class RefundReason
{
    /**
     * <code>GeneralError = 0;</code>
     */
    const GeneralError = 0;
    /**
     * <code>Fraud = 1;</code>
     */
    const Fraud = 1;
    /**
     * <code>Duplicate = 2;</code>
     */
    const Duplicate = 2;
    /**
     * <code>RequestedByCustomer = 3;</code>
     */
    const RequestedByCustomer = 3;
}

