<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product/productpb/product.proto

namespace Productpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>productpb.listRequest</code>
 */
class listRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int64 page = 1;</code>
     */
    private $page = 0;
    /**
     * <code>int64 limit = 2;</code>
     */
    private $limit = 0;

    public function __construct() {
        \GPBMetadata\Product\Productpb\Product::initOnce();
        parent::__construct();
    }

    /**
     * <code>int64 page = 1;</code>
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * <code>int64 page = 1;</code>
     */
    public function setPage($var)
    {
        GPBUtil::checkInt64($var);
        $this->page = $var;
    }

    /**
     * <code>int64 limit = 2;</code>
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * <code>int64 limit = 2;</code>
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt64($var);
        $this->limit = $var;
    }

}

