<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product/productpb/product.proto

namespace Productpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>productpb.updateRequest</code>
 */
class updateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string id = 1 [(.gogoproto.moretags) = "validate:&#92;"required,uuid4&#92;""];</code>
     */
    private $id = '';
    /**
     * <code>string name = 2 [(.gogoproto.moretags) = "validate:&#92;"required,gte=4&#92;""];</code>
     */
    private $name = '';
    /**
     * <code>bool active = 3 [(.gogoproto.moretags) = "validate:&#92;"omitempty,required&#92;""];</code>
     */
    private $active = false;
    /**
     * <code>repeated string attributes = 4 [(.gogoproto.moretags) = "validate:&#92;"dive,required&#92;""];</code>
     */
    private $attributes;
    /**
     * <code>string description = 5 [(.gogoproto.moretags) = "validate:&#92;"gt=0,lt=2056&#92;""];</code>
     */
    private $description = '';
    /**
     * <code>repeated string images = 6 [(.gogoproto.moretags) = "validate:&#92;"dive,url&#92;""];</code>
     */
    private $images;
    /**
     * <code>map&lt;string, string&gt; metadata = 7 [(.gogoproto.moretags) = "validate:&#92;"&#92;""];</code>
     */
    private $metadata;
    /**
     * <code>bool shippable = 8 [(.gogoproto.moretags) = "validate:&#92;"&#92;""];</code>
     */
    private $shippable = false;
    /**
     * <code>string url = 9 [(.gogoproto.moretags) = "validate:&#92;"omitempty,url&#92;""];</code>
     */
    private $url = '';

    public function __construct() {
        \GPBMetadata\Product\Productpb\Product::initOnce();
        parent::__construct();
    }

    /**
     * <code>string id = 1 [(.gogoproto.moretags) = "validate:&#92;"required,uuid4&#92;""];</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>string id = 1 [(.gogoproto.moretags) = "validate:&#92;"required,uuid4&#92;""];</code>
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;
    }

    /**
     * <code>string name = 2 [(.gogoproto.moretags) = "validate:&#92;"required,gte=4&#92;""];</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <code>string name = 2 [(.gogoproto.moretags) = "validate:&#92;"required,gte=4&#92;""];</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <code>bool active = 3 [(.gogoproto.moretags) = "validate:&#92;"omitempty,required&#92;""];</code>
     */
    public function getActive()
    {
        return $this->active;
    }

    /**
     * <code>bool active = 3 [(.gogoproto.moretags) = "validate:&#92;"omitempty,required&#92;""];</code>
     */
    public function setActive($var)
    {
        GPBUtil::checkBool($var);
        $this->active = $var;
    }

    /**
     * <code>repeated string attributes = 4 [(.gogoproto.moretags) = "validate:&#92;"dive,required&#92;""];</code>
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * <code>repeated string attributes = 4 [(.gogoproto.moretags) = "validate:&#92;"dive,required&#92;""];</code>
     */
    public function setAttributes(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->attributes = $arr;
    }

    /**
     * <code>string description = 5 [(.gogoproto.moretags) = "validate:&#92;"gt=0,lt=2056&#92;""];</code>
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * <code>string description = 5 [(.gogoproto.moretags) = "validate:&#92;"gt=0,lt=2056&#92;""];</code>
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;
    }

    /**
     * <code>repeated string images = 6 [(.gogoproto.moretags) = "validate:&#92;"dive,url&#92;""];</code>
     */
    public function getImages()
    {
        return $this->images;
    }

    /**
     * <code>repeated string images = 6 [(.gogoproto.moretags) = "validate:&#92;"dive,url&#92;""];</code>
     */
    public function setImages(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->images = $arr;
    }

    /**
     * <code>map&lt;string, string&gt; metadata = 7 [(.gogoproto.moretags) = "validate:&#92;"&#92;""];</code>
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * <code>map&lt;string, string&gt; metadata = 7 [(.gogoproto.moretags) = "validate:&#92;"&#92;""];</code>
     */
    public function setMetadata(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->metadata = $arr;
    }

    /**
     * <code>bool shippable = 8 [(.gogoproto.moretags) = "validate:&#92;"&#92;""];</code>
     */
    public function getShippable()
    {
        return $this->shippable;
    }

    /**
     * <code>bool shippable = 8 [(.gogoproto.moretags) = "validate:&#92;"&#92;""];</code>
     */
    public function setShippable($var)
    {
        GPBUtil::checkBool($var);
        $this->shippable = $var;
    }

    /**
     * <code>string url = 9 [(.gogoproto.moretags) = "validate:&#92;"omitempty,url&#92;""];</code>
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * <code>string url = 9 [(.gogoproto.moretags) = "validate:&#92;"omitempty,url&#92;""];</code>
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;
    }

}

