<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/digota/digota/product/productpb/product.proto

namespace Productpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>productpb.Empty</code>
 */
class PBEmpty extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\GithubCom\Digota\Digota\Product\Productpb\Product::initOnce();
        parent::__construct();
    }

}

