<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/digota/digota/product/productpb/product.proto

namespace Productpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>productpb.ProductList</code>
 */
class ProductList extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .productpb.Product products = 1;</code>
     */
    private $products;
    /**
     * <code>int32 total = 2;</code>
     */
    private $total = 0;

    public function __construct() {
        \GPBMetadata\GithubCom\Digota\Digota\Product\Productpb\Product::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .productpb.Product products = 1;</code>
     */
    public function getProducts()
    {
        return $this->products;
    }

    /**
     * <code>repeated .productpb.Product products = 1;</code>
     */
    public function setProducts(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Productpb\Product::class);
        $this->products = $arr;
    }

    /**
     * <code>int32 total = 2;</code>
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * <code>int32 total = 2;</code>
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt32($var);
        $this->total = $var;
    }

}

