<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sku/skupb/sku.proto

namespace Skupb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>skupb.inventory</code>
 */
class inventory extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int64 quantity = 1 [(.gogoproto.moretags) = "validate:&#92;"omitempty,gte=0&#92;""];</code>
     */
    private $quantity = 0;
    /**
     * <code>.skupb.inventory.Type type = 2 [(.gogoproto.moretags) = "validate:&#92;"omitempty,required,gte=0,lte=1&#92;""];</code>
     */
    private $type = 0;

    public function __construct() {
        \GPBMetadata\Sku\Skupb\Sku::initOnce();
        parent::__construct();
    }

    /**
     * <code>int64 quantity = 1 [(.gogoproto.moretags) = "validate:&#92;"omitempty,gte=0&#92;""];</code>
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * <code>int64 quantity = 1 [(.gogoproto.moretags) = "validate:&#92;"omitempty,gte=0&#92;""];</code>
     */
    public function setQuantity($var)
    {
        GPBUtil::checkInt64($var);
        $this->quantity = $var;
    }

    /**
     * <code>.skupb.inventory.Type type = 2 [(.gogoproto.moretags) = "validate:&#92;"omitempty,required,gte=0,lte=1&#92;""];</code>
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * <code>.skupb.inventory.Type type = 2 [(.gogoproto.moretags) = "validate:&#92;"omitempty,required,gte=0,lte=1&#92;""];</code>
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Skupb\inventory_Type::class);
        $this->type = $var;
    }

}

