<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sku/skupb/sku.proto

namespace Skupb;

/**
 * Protobuf enum <code>skupb.inventory.Type</code>
 */
class inventory_Type
{
    /**
     * <code>Infinite = 0;</code>
     */
    const Infinite = 0;
    /**
     * <code>Finite = 1;</code>
     */
    const Finite = 1;
}

