<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sku/skupb/sku.proto

namespace Skupb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>skupb.packageDimensions</code>
 */
class packageDimensions extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>double height = 1 [(.gogoproto.moretags) = "validate:&#92;"required,gt=0&#92;""];</code>
     */
    private $height = 0.0;
    /**
     * <code>double length = 2 [(.gogoproto.moretags) = "validate:&#92;"required,gt=0&#92;""];</code>
     */
    private $length = 0.0;
    /**
     * <code>double weight = 3 [(.gogoproto.moretags) = "validate:&#92;"required,gt=0&#92;""];</code>
     */
    private $weight = 0.0;
    /**
     * <code>double width = 4 [(.gogoproto.moretags) = "validate:&#92;"required,gt=0&#92;""];</code>
     */
    private $width = 0.0;

    public function __construct() {
        \GPBMetadata\Sku\Skupb\Sku::initOnce();
        parent::__construct();
    }

    /**
     * <code>double height = 1 [(.gogoproto.moretags) = "validate:&#92;"required,gt=0&#92;""];</code>
     */
    public function getHeight()
    {
        return $this->height;
    }

    /**
     * <code>double height = 1 [(.gogoproto.moretags) = "validate:&#92;"required,gt=0&#92;""];</code>
     */
    public function setHeight($var)
    {
        GPBUtil::checkDouble($var);
        $this->height = $var;
    }

    /**
     * <code>double length = 2 [(.gogoproto.moretags) = "validate:&#92;"required,gt=0&#92;""];</code>
     */
    public function getLength()
    {
        return $this->length;
    }

    /**
     * <code>double length = 2 [(.gogoproto.moretags) = "validate:&#92;"required,gt=0&#92;""];</code>
     */
    public function setLength($var)
    {
        GPBUtil::checkDouble($var);
        $this->length = $var;
    }

    /**
     * <code>double weight = 3 [(.gogoproto.moretags) = "validate:&#92;"required,gt=0&#92;""];</code>
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * <code>double weight = 3 [(.gogoproto.moretags) = "validate:&#92;"required,gt=0&#92;""];</code>
     */
    public function setWeight($var)
    {
        GPBUtil::checkDouble($var);
        $this->weight = $var;
    }

    /**
     * <code>double width = 4 [(.gogoproto.moretags) = "validate:&#92;"required,gt=0&#92;""];</code>
     */
    public function getWidth()
    {
        return $this->width;
    }

    /**
     * <code>double width = 4 [(.gogoproto.moretags) = "validate:&#92;"required,gt=0&#92;""];</code>
     */
    public function setWidth($var)
    {
        GPBUtil::checkDouble($var);
        $this->width = $var;
    }

}

