<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sku/skupb/sku.proto

namespace Skupb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>skupb.skuList</code>
 */
class skuList extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .skupb.sku orders = 1;</code>
     */
    private $orders;
    /**
     * <code>int32 total = 2;</code>
     */
    private $total = 0;

    public function __construct() {
        \GPBMetadata\Sku\Skupb\Sku::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .skupb.sku orders = 1;</code>
     */
    public function getOrders()
    {
        return $this->orders;
    }

    /**
     * <code>repeated .skupb.sku orders = 1;</code>
     */
    public function setOrders(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Skupb\sku::class);
        $this->orders = $arr;
    }

    /**
     * <code>int32 total = 2;</code>
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * <code>int32 total = 2;</code>
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt32($var);
        $this->total = $var;
    }

}

