<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sku/skupb/sku.proto

namespace Skupb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>skupb.updateRequest</code>
 */
class updateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string id = 1 [(.gogoproto.moretags) = "validate:&#92;"required,uuid4&#92;""];</code>
     */
    private $id = '';
    /**
     * <code>string name = 2 [(.gogoproto.moretags) = "validate:&#92;"omitempty,gt=0&#92;""];</code>
     */
    private $name = '';
    /**
     * <code>.paymentpb.currency currency = 3 [(.gogoproto.moretags) = "validate:&#92;"omitempty,required,gte=0,lte=128&#92;""];</code>
     */
    private $currency = 0;
    /**
     * <code>bool active = 4;</code>
     */
    private $active = false;
    /**
     * <code>uint64 price = 5 [(.gogoproto.moretags) = "validate:&#92;"omitempty,gte=0&#92;""];</code>
     */
    private $price = 0;
    /**
     * <code>string parent = 6 [(.gogoproto.moretags) = "validate:&#92;"omitempty,uuid4&#92;""];</code>
     */
    private $parent = '';
    /**
     * <code>map&lt;string, string&gt; metadata = 7;</code>
     */
    private $metadata;
    /**
     * <code>string image = 8 [(.gogoproto.moretags) = "validate:&#92;"omitempty,url&#92;""];</code>
     */
    private $image = '';
    /**
     * <code>.skupb.packageDimensions packageDimensions = 9 [(.gogoproto.moretags) = "validate:&#92;"omitempty,dive&#92;""];</code>
     */
    private $packageDimensions = null;
    /**
     * <code>.skupb.inventory inventory = 10 [(.gogoproto.moretags) = "validate:&#92;"omitempty,dive&#92;""];</code>
     */
    private $inventory = null;
    /**
     * <code>map&lt;string, string&gt; attributes = 11;</code>
     */
    private $attributes;

    public function __construct() {
        \GPBMetadata\Sku\Skupb\Sku::initOnce();
        parent::__construct();
    }

    /**
     * <code>string id = 1 [(.gogoproto.moretags) = "validate:&#92;"required,uuid4&#92;""];</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>string id = 1 [(.gogoproto.moretags) = "validate:&#92;"required,uuid4&#92;""];</code>
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;
    }

    /**
     * <code>string name = 2 [(.gogoproto.moretags) = "validate:&#92;"omitempty,gt=0&#92;""];</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <code>string name = 2 [(.gogoproto.moretags) = "validate:&#92;"omitempty,gt=0&#92;""];</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <code>.paymentpb.currency currency = 3 [(.gogoproto.moretags) = "validate:&#92;"omitempty,required,gte=0,lte=128&#92;""];</code>
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * <code>.paymentpb.currency currency = 3 [(.gogoproto.moretags) = "validate:&#92;"omitempty,required,gte=0,lte=128&#92;""];</code>
     */
    public function setCurrency($var)
    {
        GPBUtil::checkEnum($var, \Paymentpb\currency::class);
        $this->currency = $var;
    }

    /**
     * <code>bool active = 4;</code>
     */
    public function getActive()
    {
        return $this->active;
    }

    /**
     * <code>bool active = 4;</code>
     */
    public function setActive($var)
    {
        GPBUtil::checkBool($var);
        $this->active = $var;
    }

    /**
     * <code>uint64 price = 5 [(.gogoproto.moretags) = "validate:&#92;"omitempty,gte=0&#92;""];</code>
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * <code>uint64 price = 5 [(.gogoproto.moretags) = "validate:&#92;"omitempty,gte=0&#92;""];</code>
     */
    public function setPrice($var)
    {
        GPBUtil::checkUint64($var);
        $this->price = $var;
    }

    /**
     * <code>string parent = 6 [(.gogoproto.moretags) = "validate:&#92;"omitempty,uuid4&#92;""];</code>
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * <code>string parent = 6 [(.gogoproto.moretags) = "validate:&#92;"omitempty,uuid4&#92;""];</code>
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;
    }

    /**
     * <code>map&lt;string, string&gt; metadata = 7;</code>
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * <code>map&lt;string, string&gt; metadata = 7;</code>
     */
    public function setMetadata(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->metadata = $arr;
    }

    /**
     * <code>string image = 8 [(.gogoproto.moretags) = "validate:&#92;"omitempty,url&#92;""];</code>
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * <code>string image = 8 [(.gogoproto.moretags) = "validate:&#92;"omitempty,url&#92;""];</code>
     */
    public function setImage($var)
    {
        GPBUtil::checkString($var, True);
        $this->image = $var;
    }

    /**
     * <code>.skupb.packageDimensions packageDimensions = 9 [(.gogoproto.moretags) = "validate:&#92;"omitempty,dive&#92;""];</code>
     */
    public function getPackageDimensions()
    {
        return $this->packageDimensions;
    }

    /**
     * <code>.skupb.packageDimensions packageDimensions = 9 [(.gogoproto.moretags) = "validate:&#92;"omitempty,dive&#92;""];</code>
     */
    public function setPackageDimensions(&$var)
    {
        GPBUtil::checkMessage($var, \Skupb\packageDimensions::class);
        $this->packageDimensions = $var;
    }

    /**
     * <code>.skupb.inventory inventory = 10 [(.gogoproto.moretags) = "validate:&#92;"omitempty,dive&#92;""];</code>
     */
    public function getInventory()
    {
        return $this->inventory;
    }

    /**
     * <code>.skupb.inventory inventory = 10 [(.gogoproto.moretags) = "validate:&#92;"omitempty,dive&#92;""];</code>
     */
    public function setInventory(&$var)
    {
        GPBUtil::checkMessage($var, \Skupb\inventory::class);
        $this->inventory = $var;
    }

    /**
     * <code>map&lt;string, string&gt; attributes = 11;</code>
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * <code>map&lt;string, string&gt; attributes = 11;</code>
     */
    public function setAttributes(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->attributes = $arr;
    }

}

