<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/digota/digota/sku/skupb/sku.proto

namespace Skupb;

/**
 * Protobuf enum <code>skupb.Inventory.Type</code>
 */
class Inventory_Type
{
    /**
     * <code>Infinite = 0;</code>
     */
    const Infinite = 0;
    /**
     * <code>Finite = 1;</code>
     */
    const Finite = 1;
}

