<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.com/digota/digota/sku/skupb/sku.proto

namespace Skupb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>skupb.Empty</code>
 */
class PBEmpty extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\GithubCom\Digota\Digota\Sku\Skupb\Sku::initOnce();
        parent::__construct();
    }

}

