<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment/paymentpb/payment.proto

namespace Paymentpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>paymentpb.card</code>
 */
class card extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string Number = 1 [(.gogoproto.moretags) = "validate:&#92;"required,len=16&#92;""];</code>
     */
    private $Number = '';
    /**
     * <code>string ExpireMonth = 2 [(.gogoproto.moretags) = "validate:&#92;"required,len=2&#92;""];</code>
     */
    private $ExpireMonth = '';
    /**
     * <code>string ExpireYear = 3 [(.gogoproto.moretags) = "validate:&#92;"required,len=4&#92;""];</code>
     */
    private $ExpireYear = '';
    /**
     * <code>string FirstName = 4 [(.gogoproto.moretags) = "validate:&#92;"omitempty,min=1&#92;""];</code>
     */
    private $FirstName = '';
    /**
     * <code>string LastName = 5 [(.gogoproto.moretags) = "validate:&#92;"omitempty,min=1&#92;""];</code>
     */
    private $LastName = '';
    /**
     * <code>string CVC = 6 [(.gogoproto.moretags) = "validate:&#92;"omitempty,len=3&#92;""];</code>
     */
    private $CVC = '';
    /**
     * <code>.paymentpb.cardType type = 8 [(.gogoproto.moretags) = "validate:&#92;"required,gte=1,lte=6&#92;""];</code>
     */
    private $type = 0;

    public function __construct() {
        \GPBMetadata\Payment\Paymentpb\Payment::initOnce();
        parent::__construct();
    }

    /**
     * <code>string Number = 1 [(.gogoproto.moretags) = "validate:&#92;"required,len=16&#92;""];</code>
     */
    public function getNumber()
    {
        return $this->Number;
    }

    /**
     * <code>string Number = 1 [(.gogoproto.moretags) = "validate:&#92;"required,len=16&#92;""];</code>
     */
    public function setNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->Number = $var;
    }

    /**
     * <code>string ExpireMonth = 2 [(.gogoproto.moretags) = "validate:&#92;"required,len=2&#92;""];</code>
     */
    public function getExpireMonth()
    {
        return $this->ExpireMonth;
    }

    /**
     * <code>string ExpireMonth = 2 [(.gogoproto.moretags) = "validate:&#92;"required,len=2&#92;""];</code>
     */
    public function setExpireMonth($var)
    {
        GPBUtil::checkString($var, True);
        $this->ExpireMonth = $var;
    }

    /**
     * <code>string ExpireYear = 3 [(.gogoproto.moretags) = "validate:&#92;"required,len=4&#92;""];</code>
     */
    public function getExpireYear()
    {
        return $this->ExpireYear;
    }

    /**
     * <code>string ExpireYear = 3 [(.gogoproto.moretags) = "validate:&#92;"required,len=4&#92;""];</code>
     */
    public function setExpireYear($var)
    {
        GPBUtil::checkString($var, True);
        $this->ExpireYear = $var;
    }

    /**
     * <code>string FirstName = 4 [(.gogoproto.moretags) = "validate:&#92;"omitempty,min=1&#92;""];</code>
     */
    public function getFirstName()
    {
        return $this->FirstName;
    }

    /**
     * <code>string FirstName = 4 [(.gogoproto.moretags) = "validate:&#92;"omitempty,min=1&#92;""];</code>
     */
    public function setFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->FirstName = $var;
    }

    /**
     * <code>string LastName = 5 [(.gogoproto.moretags) = "validate:&#92;"omitempty,min=1&#92;""];</code>
     */
    public function getLastName()
    {
        return $this->LastName;
    }

    /**
     * <code>string LastName = 5 [(.gogoproto.moretags) = "validate:&#92;"omitempty,min=1&#92;""];</code>
     */
    public function setLastName($var)
    {
        GPBUtil::checkString($var, True);
        $this->LastName = $var;
    }

    /**
     * <code>string CVC = 6 [(.gogoproto.moretags) = "validate:&#92;"omitempty,len=3&#92;""];</code>
     */
    public function getCVC()
    {
        return $this->CVC;
    }

    /**
     * <code>string CVC = 6 [(.gogoproto.moretags) = "validate:&#92;"omitempty,len=3&#92;""];</code>
     */
    public function setCVC($var)
    {
        GPBUtil::checkString($var, True);
        $this->CVC = $var;
    }

    /**
     * <code>.paymentpb.cardType type = 8 [(.gogoproto.moretags) = "validate:&#92;"required,gte=1,lte=6&#92;""];</code>
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * <code>.paymentpb.cardType type = 8 [(.gogoproto.moretags) = "validate:&#92;"required,gte=1,lte=6&#92;""];</code>
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Paymentpb\cardType::class);
        $this->type = $var;
    }

}

