<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment/paymentpb/payment.proto

namespace Paymentpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>paymentpb.chargeList</code>
 */
class chargeList extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .paymentpb.charge charges = 1;</code>
     */
    private $charges;
    /**
     * <code>int32 total = 2;</code>
     */
    private $total = 0;

    public function __construct() {
        \GPBMetadata\Payment\Paymentpb\Payment::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .paymentpb.charge charges = 1;</code>
     */
    public function getCharges()
    {
        return $this->charges;
    }

    /**
     * <code>repeated .paymentpb.charge charges = 1;</code>
     */
    public function setCharges(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Paymentpb\charge::class);
        $this->charges = $arr;
    }

    /**
     * <code>int32 total = 2;</code>
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * <code>int32 total = 2;</code>
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt32($var);
        $this->total = $var;
    }

}

