<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment/paymentpb/payment.proto

namespace Paymentpb;

/**
 * Protobuf enum <code>paymentpb.chargeStatus</code>
 */
class chargeStatus
{
    /**
     * <code>Paid = 0;</code>
     */
    const Paid = 0;
    /**
     * <code>Refunded = 1;</code>
     */
    const Refunded = 1;
}

