<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment/paymentpb/payment.proto

namespace Paymentpb;

/**
 * Protobuf enum <code>paymentpb.currency</code>
 */
class currency
{
    /**
     * <code>CUR_RESERVED = 0;</code>
     */
    const CUR_RESERVED = 0;
    /**
     * <code>AFN = 1;</code>
     */
    const AFN = 1;
    /**
     * <code>ALL = 2;</code>
     */
    const ALL = 2;
    /**
     * <code>AMD = 3;</code>
     */
    const AMD = 3;
    /**
     * <code>ANG = 4;</code>
     */
    const ANG = 4;
    /**
     * <code>ARS = 5;</code>
     */
    const ARS = 5;
    /**
     * <code>AUD = 6;</code>
     */
    const AUD = 6;
    /**
     * <code>AWG = 7;</code>
     */
    const AWG = 7;
    /**
     * <code>AZN = 8;</code>
     */
    const AZN = 8;
    /**
     * <code>BAM = 9;</code>
     */
    const BAM = 9;
    /**
     * <code>BBD = 10;</code>
     */
    const BBD = 10;
    /**
     * <code>BGN = 11;</code>
     */
    const BGN = 11;
    /**
     * <code>BHD = 12;</code>
     */
    const BHD = 12;
    /**
     * <code>BMD = 13;</code>
     */
    const BMD = 13;
    /**
     * <code>BND = 14;</code>
     */
    const BND = 14;
    /**
     * <code>BOB = 15;</code>
     */
    const BOB = 15;
    /**
     * <code>BRL = 16;</code>
     */
    const BRL = 16;
    /**
     * <code>BSD = 17;</code>
     */
    const BSD = 17;
    /**
     * <code>BWP = 18;</code>
     */
    const BWP = 18;
    /**
     * <code>BYN = 19;</code>
     */
    const BYN = 19;
    /**
     * <code>BYR = 20;</code>
     */
    const BYR = 20;
    /**
     * <code>BZD = 21;</code>
     */
    const BZD = 21;
    /**
     * <code>CAD = 22;</code>
     */
    const CAD = 22;
    /**
     * <code>CLP = 23;</code>
     */
    const CLP = 23;
    /**
     * <code>CNY = 24;</code>
     */
    const CNY = 24;
    /**
     * <code>COP = 25;</code>
     */
    const COP = 25;
    /**
     * <code>CRC = 26;</code>
     */
    const CRC = 26;
    /**
     * <code>CUP = 27;</code>
     */
    const CUP = 27;
    /**
     * <code>CZK = 28;</code>
     */
    const CZK = 28;
    /**
     * <code>DKK = 29;</code>
     */
    const DKK = 29;
    /**
     * <code>DOP = 30;</code>
     */
    const DOP = 30;
    /**
     * <code>DZD = 31;</code>
     */
    const DZD = 31;
    /**
     * <code>EEK = 32;</code>
     */
    const EEK = 32;
    /**
     * <code>EGP = 33;</code>
     */
    const EGP = 33;
    /**
     * <code>EUR = 34;</code>
     */
    const EUR = 34;
    /**
     * <code>FJD = 35;</code>
     */
    const FJD = 35;
    /**
     * <code>FKP = 36;</code>
     */
    const FKP = 36;
    /**
     * <code>GBP = 37;</code>
     */
    const GBP = 37;
    /**
     * <code>GGP = 38;</code>
     */
    const GGP = 38;
    /**
     * <code>GHC = 39;</code>
     */
    const GHC = 39;
    /**
     * <code>GIP = 40;</code>
     */
    const GIP = 40;
    /**
     * <code>GTQ = 41;</code>
     */
    const GTQ = 41;
    /**
     * <code>GYD = 42;</code>
     */
    const GYD = 42;
    /**
     * <code>HKD = 43;</code>
     */
    const HKD = 43;
    /**
     * <code>HNL = 44;</code>
     */
    const HNL = 44;
    /**
     * <code>HRK = 45;</code>
     */
    const HRK = 45;
    /**
     * <code>HUF = 46;</code>
     */
    const HUF = 46;
    /**
     * <code>IDR = 47;</code>
     */
    const IDR = 47;
    /**
     * <code>ILS = 48;</code>
     */
    const ILS = 48;
    /**
     * <code>IMP = 49;</code>
     */
    const IMP = 49;
    /**
     * <code>INR = 50;</code>
     */
    const INR = 50;
    /**
     * <code>IQD = 51;</code>
     */
    const IQD = 51;
    /**
     * <code>IRR = 52;</code>
     */
    const IRR = 52;
    /**
     * <code>ISK = 53;</code>
     */
    const ISK = 53;
    /**
     * <code>JEP = 54;</code>
     */
    const JEP = 54;
    /**
     * <code>JMD = 55;</code>
     */
    const JMD = 55;
    /**
     * <code>JOD = 56;</code>
     */
    const JOD = 56;
    /**
     * <code>JPY = 57;</code>
     */
    const JPY = 57;
    /**
     * <code>KES = 58;</code>
     */
    const KES = 58;
    /**
     * <code>KGS = 59;</code>
     */
    const KGS = 59;
    /**
     * <code>KHR = 60;</code>
     */
    const KHR = 60;
    /**
     * <code>KPW = 61;</code>
     */
    const KPW = 61;
    /**
     * <code>KRW = 62;</code>
     */
    const KRW = 62;
    /**
     * <code>KWD = 63;</code>
     */
    const KWD = 63;
    /**
     * <code>KYD = 64;</code>
     */
    const KYD = 64;
    /**
     * <code>KZT = 65;</code>
     */
    const KZT = 65;
    /**
     * <code>LAK = 66;</code>
     */
    const LAK = 66;
    /**
     * <code>LBP = 67;</code>
     */
    const LBP = 67;
    /**
     * <code>LKR = 68;</code>
     */
    const LKR = 68;
    /**
     * <code>LRD = 69;</code>
     */
    const LRD = 69;
    /**
     * <code>LTL = 70;</code>
     */
    const LTL = 70;
    /**
     * <code>LVL = 71;</code>
     */
    const LVL = 71;
    /**
     * <code>LYD = 72;</code>
     */
    const LYD = 72;
    /**
     * <code>MAD = 73;</code>
     */
    const MAD = 73;
    /**
     * <code>MKD = 74;</code>
     */
    const MKD = 74;
    /**
     * <code>MNT = 75;</code>
     */
    const MNT = 75;
    /**
     * <code>MUR = 76;</code>
     */
    const MUR = 76;
    /**
     * <code>MXN = 77;</code>
     */
    const MXN = 77;
    /**
     * <code>MWK = 78;</code>
     */
    const MWK = 78;
    /**
     * <code>MYR = 79;</code>
     */
    const MYR = 79;
    /**
     * <code>MZN = 80;</code>
     */
    const MZN = 80;
    /**
     * <code>NAD = 81;</code>
     */
    const NAD = 81;
    /**
     * <code>NGN = 82;</code>
     */
    const NGN = 82;
    /**
     * <code>NIO = 83;</code>
     */
    const NIO = 83;
    /**
     * <code>NOK = 84;</code>
     */
    const NOK = 84;
    /**
     * <code>NPR = 85;</code>
     */
    const NPR = 85;
    /**
     * <code>NZD = 86;</code>
     */
    const NZD = 86;
    /**
     * <code>OMR = 87;</code>
     */
    const OMR = 87;
    /**
     * <code>PAB = 88;</code>
     */
    const PAB = 88;
    /**
     * <code>PEN = 89;</code>
     */
    const PEN = 89;
    /**
     * <code>PHP = 90;</code>
     */
    const PHP = 90;
    /**
     * <code>PKR = 91;</code>
     */
    const PKR = 91;
    /**
     * <code>PLN = 92;</code>
     */
    const PLN = 92;
    /**
     * <code>PYG = 93;</code>
     */
    const PYG = 93;
    /**
     * <code>QAR = 94;</code>
     */
    const QAR = 94;
    /**
     * <code>RON = 95;</code>
     */
    const RON = 95;
    /**
     * <code>RSD = 96;</code>
     */
    const RSD = 96;
    /**
     * <code>RUB = 97;</code>
     */
    const RUB = 97;
    /**
     * <code>RUR = 98;</code>
     */
    const RUR = 98;
    /**
     * <code>SAR = 99;</code>
     */
    const SAR = 99;
    /**
     * <code>SBD = 100;</code>
     */
    const SBD = 100;
    /**
     * <code>SCR = 101;</code>
     */
    const SCR = 101;
    /**
     * <code>SEK = 102;</code>
     */
    const SEK = 102;
    /**
     * <code>SGD = 103;</code>
     */
    const SGD = 103;
    /**
     * <code>SHP = 104;</code>
     */
    const SHP = 104;
    /**
     * <code>SOS = 105;</code>
     */
    const SOS = 105;
    /**
     * <code>SRD = 106;</code>
     */
    const SRD = 106;
    /**
     * <code>SVC = 107;</code>
     */
    const SVC = 107;
    /**
     * <code>SYP = 108;</code>
     */
    const SYP = 108;
    /**
     * <code>THB = 109;</code>
     */
    const THB = 109;
    /**
     * <code>TND = 110;</code>
     */
    const TND = 110;
    /**
     * <code>TRL = 111;</code>
     */
    const TRL = 111;
    /**
     * <code>TRY = 112;</code>
     */
    const TRY = 112;
    /**
     * <code>TTD = 113;</code>
     */
    const TTD = 113;
    /**
     * <code>TWD = 114;</code>
     */
    const TWD = 114;
    /**
     * <code>TZS = 115;</code>
     */
    const TZS = 115;
    /**
     * <code>UAH = 116;</code>
     */
    const UAH = 116;
    /**
     * <code>UGX = 117;</code>
     */
    const UGX = 117;
    /**
     * <code>AED = 118;</code>
     */
    const AED = 118;
    /**
     * <code>UYU = 119;</code>
     */
    const UYU = 119;
    /**
     * <code>UZS = 120;</code>
     */
    const UZS = 120;
    /**
     * <code>VEF = 121;</code>
     */
    const VEF = 121;
    /**
     * <code>VND = 122;</code>
     */
    const VND = 122;
    /**
     * <code>XCD = 123;</code>
     */
    const XCD = 123;
    /**
     * <code>YER = 124;</code>
     */
    const YER = 124;
    /**
     * <code>ZAR = 125;</code>
     */
    const ZAR = 125;
    /**
     * <code>ZMW = 126;</code>
     */
    const ZMW = 126;
    /**
     * <code>ZWD = 127;</code>
     */
    const ZWD = 127;
    /**
     * <code>USD = 128;</code>
     */
    const USD = 128;
}

