<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment/paymentpb/payment.proto

namespace Paymentpb;

/**
 * Protobuf enum <code>paymentpb.paymentProviderId</code>
 */
class paymentProviderId
{
    /**
     * <code>PROVIDER_Reserved = 0;</code>
     */
    const PROVIDER_Reserved = 0;
    /**
     * <code>Stripe = 1;</code>
     */
    const Stripe = 1;
    /**
     * <code>Paypal = 2;</code>
     */
    const Paypal = 2;
    /**
     * <code>Braintree = 3;</code>
     */
    const Braintree = 3;
}

