<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment/paymentpb/payment.proto

namespace Paymentpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>paymentpb.refund</code>
 */
class refund extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>uint64 refundAmount = 1;</code>
     */
    private $refundAmount = 0;
    /**
     * <code>string providerRefundId = 2;</code>
     */
    private $providerRefundId = '';
    /**
     * <code>.paymentpb.refundReason reason = 3;</code>
     */
    private $reason = 0;
    /**
     * <code>int64 created = 4;</code>
     */
    private $created = 0;

    public function __construct() {
        \GPBMetadata\Payment\Paymentpb\Payment::initOnce();
        parent::__construct();
    }

    /**
     * <code>uint64 refundAmount = 1;</code>
     */
    public function getRefundAmount()
    {
        return $this->refundAmount;
    }

    /**
     * <code>uint64 refundAmount = 1;</code>
     */
    public function setRefundAmount($var)
    {
        GPBUtil::checkUint64($var);
        $this->refundAmount = $var;
    }

    /**
     * <code>string providerRefundId = 2;</code>
     */
    public function getProviderRefundId()
    {
        return $this->providerRefundId;
    }

    /**
     * <code>string providerRefundId = 2;</code>
     */
    public function setProviderRefundId($var)
    {
        GPBUtil::checkString($var, True);
        $this->providerRefundId = $var;
    }

    /**
     * <code>.paymentpb.refundReason reason = 3;</code>
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * <code>.paymentpb.refundReason reason = 3;</code>
     */
    public function setReason($var)
    {
        GPBUtil::checkEnum($var, \Paymentpb\refundReason::class);
        $this->reason = $var;
    }

    /**
     * <code>int64 created = 4;</code>
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * <code>int64 created = 4;</code>
     */
    public function setCreated($var)
    {
        GPBUtil::checkInt64($var);
        $this->created = $var;
    }

}

