<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment/paymentpb/payment.proto

namespace Paymentpb;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>paymentpb.refundRequest</code>
 */
class refundRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string id = 1 [(.gogoproto.moretags) = "validate:&#92;"uuid4,required&#92;""];</code>
     */
    private $id = '';
    /**
     * <code>uint64 amount = 2;</code>
     */
    private $amount = 0;
    /**
     * <code>.paymentpb.refundReason reason = 3 [(.gogoproto.moretags) = "validate:&#92;"omitempty,gte=0,lte=3&#92;""];</code>
     */
    private $reason = 0;

    public function __construct() {
        \GPBMetadata\Payment\Paymentpb\Payment::initOnce();
        parent::__construct();
    }

    /**
     * <code>string id = 1 [(.gogoproto.moretags) = "validate:&#92;"uuid4,required&#92;""];</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <code>string id = 1 [(.gogoproto.moretags) = "validate:&#92;"uuid4,required&#92;""];</code>
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;
    }

    /**
     * <code>uint64 amount = 2;</code>
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * <code>uint64 amount = 2;</code>
     */
    public function setAmount($var)
    {
        GPBUtil::checkUint64($var);
        $this->amount = $var;
    }

    /**
     * <code>.paymentpb.refundReason reason = 3 [(.gogoproto.moretags) = "validate:&#92;"omitempty,gte=0,lte=3&#92;""];</code>
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * <code>.paymentpb.refundReason reason = 3 [(.gogoproto.moretags) = "validate:&#92;"omitempty,gte=0,lte=3&#92;""];</code>
     */
    public function setReason($var)
    {
        GPBUtil::checkEnum($var, \Paymentpb\refundReason::class);
        $this->reason = $var;
    }

}

